version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
  restore_dep_cache: &restore_dep_cache
    restore_cache:
      keys:
        - v2-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
  filter_any: &filter_any
    filters:
      tags:
        only: /.*/
  filter_tags: &filter_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^\d+\.\d+\.\d+.*/

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  dependencies:
    <<: *container_config
    steps:
      - checkout
      - *restore_dep_cache
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  lint:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
      - codecov/upload:
          file: coverage/coverage-final.json
  build:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prune
          command: npm prune --production
      - run:
          name: Copy Meta
          command: |
            cp package.json ./dist
            cp package-lock.json ./dist
            cp LICENSE ./dist
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  publish:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish
          command: npm publish ./dist

workflows:
  version: 2
  default:
    jobs:
      - dependencies:
          <<: *filter_any
      - lint:
          requires:
            - dependencies
          <<: *filter_any
      - test:
          requires:
            - dependencies
          <<: *filter_any
      - build:
          requires:
            - lint
            - test
          <<: *filter_any
      - publish:
          requires:
            - build
          <<: *filter_tags